services:
  - type: web
    name: neutron
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
